# Generated by Django 4.1.7 on 2023-05-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webshop_user_id', models.CharField(max_length=100)),
                ('webshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.webshop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webshop_product_id', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('webshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.webshop')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
                ('webshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.webshop')),
            ],
        ),
    ]
